Repository giotto-ai/giotto-tda, pull requests merged in 2020-01, with the labels that each got.

#162 Add recommendations for developer install to avoid C++ woes
  README.rst
Labels: documentation

#189 Minor mapper enhancements
  examples/mapper_quickstart.ipynb
  giotto/mapper/cluster.py
  giotto/mapper/cover.py
  giotto/mapper/nerve.py
  giotto/mapper/pipeline.py
Labels: mapper

#205 Attempt to fix manylinux2010 builds for python 3.8
  azure-ci/docker_scripts.sh
Labels: bug

#204 Fix link to azure pipelines in badge
  README.rst
Labels: bug

#203 Docs/tidyup docstrings
  README.rst
  doc/conf.py
  gtda/mapper/cluster.py
  gtda/mapper/cover.py
  gtda/mapper/filter.py
  gtda/mapper/pipeline.py
  gtda/mapper/tests/test_cover.py
  gtda/mapper/visualization.py
Labels: documentation, enhancement

#202 Minor mapper enhancements
  examples/mapper_quickstart.ipynb
  gtda/mapper/cluster.py
  gtda/mapper/cover.py
  gtda/mapper/pipeline.py
  gtda/mapper/utils/_cluster.py
  gtda/mapper/utils/_cover.py
  gtda/mapper/visualization.py
  gtda/utils/validation.py
Labels: enhancement

#211 Last preparations for 0.1.4
  .azure-ci/build_manylinux2010.sh
  .azure-ci/docker_scripts.sh
  .tools/git-pre-commit
  CONTRIBUTING.rst
  README.rst
  azure-pipelines.yml
  requirements.txt
Labels: enhancement
