Repository giotto-ai/giotto-tda, pull requests merged in 2020-03, with the labels that each got.

#346 Point dosctrings of rescaling functions to point_clouds
  gtda/point_clouds/rescaling.py
Labels: documentation

#258 Fix docstring for PersistenceImage
  gtda/diagrams/features.py
Labels: discussion, documentation

#351 Refactor validate_params
  doc/index.rst
  examples/plotting.py
  gtda/base.py
  gtda/diagrams/_metrics.py
  gtda/diagrams/distance.py
  gtda/diagrams/features.py
  gtda/diagrams/preprocessing.py
  gtda/diagrams/tests/test_distance.py
  gtda/diagrams/tests/test_features.py
  gtda/diagrams/tests/test_preprocessing.py
  gtda/graphs/transition.py
  gtda/homology/cubical.py
  gtda/homology/simplicial.py
  gtda/images/filtrations.py
  gtda/images/preprocessing.py
  gtda/images/tests/test_filtrations.py
  gtda/mapper/__init__.py
  gtda/mapper/cluster.py
  gtda/mapper/cover.py
  gtda/mapper/tests/test_cover.py
  gtda/mapper/utils/_logging.py
  gtda/mapper/utils/visualization.py
  gtda/pipeline.py
  gtda/point_clouds/rescaling.py
  gtda/time_series/embedding.py
  gtda/time_series/multivariate.py
  gtda/time_series/preprocessing.py
  gtda/time_series/target.py
  gtda/utils/__init__.py
  gtda/utils/intervals.py
  gtda/utils/tests/test_validation.py
  gtda/utils/validation.py
  setup.cfg
Labels: enhancement

#359 Change parenthesis in glossary
  CODE_AUTHORS
  doc/theory/glossary.tex
Labels: documentation

#306 Ghpages
  .gitignore
  CONTRIBUTING.rst
  README.rst
  azure-pipelines.yml
  doc/Makefile
  doc/conf.py
  doc/contributing/index.rst
  doc/faq.rst
  doc/images/mapper_pipeline.svg
  doc/images/tda_logo.svg
  doc/index.rst
  doc/installation.rst
  doc/ipynb_to_py.py
  doc/library.rst
  doc/modules/base.rst
  doc/modules/diagrams.rst
  doc/modules/graphs.rst
  doc/modules/homology.rst
  doc/modules/images.rst
  doc/modules/index.rst
  doc/modules/mapper.rst
  doc/modules/meta_transformers.rst
  doc/modules/pipeline.rst
  doc/modules/point_clouds.rst
  doc/modules/time_series.rst
  doc/modules/validation.rst
  doc/notebooks/advanced.rst
  doc/notebooks/basic.rst
  doc/notebooks/index.rst
  doc/release.rst
  doc/source/_static/style.css
  doc/templates/class.rst
  doc/templates/class_with_call.rst
  doc/templates/class_without_init.rst
  doc/templates/deprecated_class.rst
  doc/templates/deprecated_class_with_call.rst
  doc/templates/deprecated_class_without_init.rst
  doc/templates/deprecated_function.rst
  doc/templates/function.rst
  doc/templates/layout.html
  doc/theory/glossary.tex
  doc/update_versions.py
  examples/classifying_shapes.ipynb
  examples/datasets.py
  examples/lorenz_attractor.ipynb
  examples/mapper_quickstart.ipynb
  examples/vietoris_rips_quickstart.ipynb
  examples/voids_on_the_plane.ipynb
  gtda/diagrams/distance.py
  gtda/diagrams/features.py
  gtda/diagrams/preprocessing.py
  gtda/homology/cubical.py
  gtda/homology/simplicial.py
  gtda/mapper/pipeline.py
  gtda/point_clouds/rescaling.py
  gtda/time_series/embedding.py
  setup.cfg
  setup.py
Labels: documentation, enhancement, theory

#318 Pcs different sizes
  CONTRIBUTING.rst
  PULL_REQUEST_TEMPLATE.md
  README.rst
  doc/modules/validation.rst
  examples/plotting_api.ipynb
  gtda/__init__.py
  gtda/base.py
  gtda/diagrams/representations.py
  gtda/graphs/geodesic_distance.py
  gtda/graphs/kneighbors.py
  gtda/graphs/transition.py
  gtda/homology/cubical.py
  gtda/homology/simplicial.py
  gtda/homology/tests/test_simplicial.py
  gtda/images/_utils.py
  gtda/images/filtrations.py
  gtda/images/preprocessing.py
  gtda/images/tests/test_preprocessing.py
  gtda/mapper/cover.py
  gtda/mapper/filter.py
  gtda/plotting/images.py
  gtda/point_clouds/rescaling.py
  gtda/time_series/embedding.py
  gtda/time_series/features.py
  gtda/time_series/multivariate.py
  gtda/time_series/preprocessing.py
  gtda/utils/__init__.py
  gtda/utils/validation.py
Labels: enhancement
