Repository giotto-ai/giotto-tda, pull requests merged in 2020-02, with the labels that each got.

#260 Add global node ID to Mapper tooltip and remove pullback cover set label
  examples/mapper_quickstart.ipynb
  gtda/mapper/nerve.py
  gtda/mapper/pipeline.py
  gtda/mapper/utils/visualization.py
  gtda/mapper/visualization.py
Labels: enhancement, mapper

#268 Drop support for Python 3.5
  README.rst
  azure-pipelines.yml
  setup.py
Labels: enhancement

#278 Place pytest and flake8 tests on dev install before dev uninstall
  azure-pipelines.yml
Labels: CI, enhancement

#280 Use a version of papermill that does not produce a warning
  azure-pipelines.yml
Labels: CI

#257 Glossary: cubical complex entry
  CODE_AUTHORS
  doc/theory/bibliography.bib
  doc/theory/glossary.tex
Labels: theory

#281 Change order between uninstall and testing steps in .azure-ci/docker_scripts.sh
  .azure-ci/docker_scripts.sh
Labels: CI

#277 Fix/mapper colors
  examples/mapper_quickstart.ipynb
  gtda/mapper/utils/visualization.py
Labels: mapper

#285 Preparations for first nightly release
  .azure-ci/docker_scripts.sh
  README.rst
  azure-pipelines.yml
  gtda/utils/tests/test_validation.py
Labels: CI

#274 Use ccache in CI
  .azure-ci/build_manylinux2010.sh
  .azure-ci/docker_scripts.sh
  .azure-ci/setup_ccache.sh
  azure-pipelines.yml
Labels: CI

#293 Remove redundant CI jobs
  azure-pipelines.yml
Labels: CI

#296 Ability to trigger wheels testing on jupyter notebooks only on a single OS
  azure-pipelines.yml
Labels: CI

#273 CI Always exit on failure
  .azure-ci/build_manylinux2010.sh
  .azure-ci/docker_scripts.sh
  azure-pipelines.yml
Labels: CI, enhancement

#302 Keep flake8 checks only in macOS jobs
  .azure-ci/docker_scripts.sh
  azure-pipelines.yml
Labels: CI

#305 Remove progress bars display in docker_scripts.sh
  .azure-ci/docker_scripts.sh
Labels: CI

#287 Combine extra dependencies into single setup.py keys
  .azure-ci/docker_scripts.sh
  README.rst
  azure-pipelines.yml
  setup.py
Labels: enhancement

#304 Move bindings modules
  CMakeLists.txt
  gtda/diagrams/_metrics.py
  gtda/externals/bindings/bottleneck_bindings.cpp
  gtda/externals/bindings/cech_complex_bindings.cpp
  gtda/externals/bindings/cubical_complex_bindings.cpp
  gtda/externals/bindings/periodic_cubical_complex_bindings.cpp
  gtda/externals/bindings/persistent_cohomology_bindings.cpp
  gtda/externals/bindings/rips_complex_bindings.cpp
  gtda/externals/bindings/ripser_bindings.cpp
  gtda/externals/bindings/simplex_tree_bindings.cpp
  gtda/externals/bindings/strong_witness_complex_bindings.cpp
  gtda/externals/bindings/wasserstein_bindings.cpp
  gtda/externals/bindings/witness_complex_bindings.cpp
  gtda/externals/python/cech_complex_interface.py
  gtda/externals/python/cubical_complex_interface.py
  gtda/externals/python/periodic_cubical_complex_interface.py
  gtda/externals/python/rips_complex_interface.py
  gtda/externals/python/ripser_interface.py
  gtda/externals/python/simplex_tree_interface.py
  gtda/externals/python/strong_witness_complex_interface.py
  gtda/externals/python/witness_complex_interface.py
  setup.py
Labels: enhancement

#317 Remove packaging of source distribution
  .azure-ci/docker_scripts.sh
  azure-pipelines.yml
Labels: CI, enhancement

#312 Run auditwheel repair for manylinux2010 wheels
  .azure-ci/docker_scripts.sh
  azure-pipelines.yml
Labels: CI

#323 Bump joblib required version to 0.13
  README.rst
  gtda/pipeline.py
  requirements.txt
Labels: enhancement

#321 Replace string formatting with f-strings except in setup and validation
  examples/plotting.py
  gtda/diagrams/tests/test_features.py
  gtda/mapper/cluster.py
  gtda/mapper/cover.py
  gtda/mapper/pipeline.py
  gtda/mapper/tests/test_cover.py
  gtda/mapper/utils/visualization.py
  gtda/pipeline.py
  gtda/utils/_docs.py
  setup.py
Labels: enhancement

#320 Glossary hyperrefs
  doc/theory/glossary.tex
Labels: theory

#247 Silhouette
  doc/index.rst
  doc/theory/bibliography.bib
  doc/theory/glossary.tex
  gtda/diagrams/__init__.py
  gtda/diagrams/_metrics.py
  gtda/diagrams/_utils.py
  gtda/diagrams/distance.py
  gtda/diagrams/features.py
  gtda/diagrams/tests/test_features.py
  gtda/utils/validation.py
Labels: enhancement

#300 Adds SignedDistanceFiltration
  gtda/images/__init__.py
  gtda/images/_utils.py
  gtda/images/filtrations.py
  gtda/images/tests/test_filtrations.py
Labels: enhancement

#242 Fixes ConsistentRescaling hyperparams mutability and adds ConsecutiveRescaling
  gtda/homology/__init__.py
  gtda/homology/consistent.py
  gtda/homology/rescaling.py
  gtda/homology/tests/test_consistent.py
  gtda/homology/tests/test_rescaling.py
Labels: enhancement

#329 Fix array checks in image submodules
  examples/plotting.py
  gtda/images/filtrations.py
  gtda/images/preprocessing.py
  gtda/images/tests/test_filtrations.py
  gtda/mapper/tests/test_cluster.py
  gtda/mapper/tests/test_visualization.py
  gtda/mapper/utils/visualization.py
  gtda/time_series/tests/test_target.py
Labels: enhancement

#319 Run scikit-learn common tests for image.preprocessing.Binarizer, Inverter
  gtda/tests/test_common.py
Labels: enhancement

#331 Creates point_clouds submodule and update doc/index.rst
  doc/index.rst
  gtda/__init__.py
  gtda/homology/__init__.py
  gtda/homology/cubical.py
  gtda/homology/simplicial.py
  gtda/homology/tests/test_cubical.py
  gtda/homology/tests/test_simplicial.py
  gtda/images/filtrations.py
  gtda/point_clouds/__init__.py
  gtda/point_clouds/rescaling.py
  gtda/point_clouds/tests/__init__.py
  gtda/point_clouds/tests/test_rescaling.py
Labels: documentation, enhancement

#333 Correct and document utils/validate_params
  gtda/diagrams/features.py
  gtda/diagrams/preprocessing.py
  gtda/graphs/transition.py
  gtda/homology/cubical.py
  gtda/homology/simplicial.py
  gtda/time_series/target.py
  gtda/utils/tests/test_validation.py
  gtda/utils/validation.py
Labels: enhancement
